AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-rspec
  - rubocop-rake

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false
