# frozen_string_literal: true

require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task default: :spec

desc 'Run the end-to-end client benchmark harness (server must be running)'
task :bench do
  ruby 'bench/bench.rb'
end

desc 'Start an IRB console with the gem loaded'
task :console do
  require 'irb'
  require_relative 'lib/emb'
  ARGV.clear
  IRB.start
end
