AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-rake

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/emb-server.rb
