# frozen_string_literal: true

require 'rubocop/rake_task'

RuboCop::RakeTask.new

desc 'Start an IRB console with the gem loaded'
task :console do
  require 'irb'
  require_relative 'lib/emb-server'
  ARGV.clear
  IRB.start
end

task default: :rubocop
